"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'accounts',
    'books',
    'libraries',
    'reviews',
    'galfies',
    'comments',
    'django_extensions', # 장고 확장 기능 제공하는 툴
    'rest_framework', 
    'rest_framework.authtoken', # dj-rest-auth 관련 설정 - start
    'dj_rest_auth',
    'drf_spectacular', # Swagger(OpenAPI) 스펙 자동 생성을 위한 앱
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration', # dj-rest-auth 관련 설정 - end
    'debug_toolbar', # 디버깅할 때 참고할 자료를 제공하는 툴. 개발모드에서만 실행
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

SITE_ID = 1 # dj-rest-auth 관련 설정

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware', # 디버그 툴바 관련 설정
    'allauth.account.middleware.AccountMiddleware', # dj-rest-auth 관련 설정
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# 정적파일 서빙할 폴더 경로 지정 
STATIC_URL = '/static/'   # 템플릿에서 불러올 URL (정적 파일을 참조할 URL prefix)
STATICFILES_DIRS = [ BASE_DIR / "static" ]   # 개발용 공용 static 경로
STATIC_ROOT = BASE_DIR / "staticfiles"     # collectstatic 결과물 저장 폴더

# 동적파일을 저장할 폴더 경로 지정
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 디버그 툴바가 로컬에서만 보이게끔 하는 보안 설정. 
INTERNAL_IPS = [
    "127.0.0.1", 
]


AUTH_USER_MODEL = 'accounts.User' 
ACCOUNT_EMAIL_VERIFICATION = 'none' # dj-rest-auth 이메일 인증 비활성화

# dj-rest-auth 커스텀한 시리얼라이저 등록
REST_AUTH = {
    'LOGIN_SERIALIZER': 'accounts.accounts_serializers.serializers.CustomLoginSerializer',
    'USER_DETAILS_SERIALIZER': 'accounts.accounts_serializers.serializers.CustomUserDetailsSerializer',
    'REGISTER_SERIALIZER': 'accounts.accounts_serializers.serializers.CustomSignupSerializer',
}


REST_FRAMEWORK = {
    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # permission
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny', # 전역 권한은 모든 사용자 접근 허용(AllowAny)
    ],
    # DRF가 기본으로 사용할 Schema Generator 지정
    # Swagger(OpenAPI) 문서를 생성하는 엔진을 drf-spectacular로 바꿈
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# swagger 설정
SPECTACULAR_SETTINGS = {
    'TITLE': 'Bookmark API',
    'DESCRIPTION': '독서 리뷰 및 갈피 서비스 API 문서',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # Swagger UI에서 인증 버튼 활성화
    'COMPONENT_SPLIT_REQUEST': True,  # request/response 예시를 Swagger에 표시
    'DISABLE_ERRORS_AND_WARNINGS': False, # 경로 충돌 시 경고를 무시하지 않도록 함.
}
