INSERT INTO books_category (id, name) VALUES (1, '가정/요리/뷰티');
INSERT INTO books_category (id, name) VALUES (2, '건강/취미/레저');
INSERT INTO books_category (id, name) VALUES (3, '경제경영');
INSERT INTO books_category (id, name) VALUES (4, '고등학교참고서');
INSERT INTO books_category (id, name) VALUES (5, '고전');
INSERT INTO books_category (id, name) VALUES (6, '과학');
INSERT INTO books_category (id, name) VALUES (7, '금강산 여행 가는 이에게');
INSERT INTO books_category (id, name) VALUES (8, '달력/기타');
INSERT INTO books_category (id, name) VALUES (9, '대학교재/전문서적');
INSERT INTO books_category (id, name) VALUES (10, '만화');
INSERT INTO books_category (id, name) VALUES (11, '사회과학');
INSERT INTO books_category (id, name) VALUES (12, '소설/시/희곡');
INSERT INTO books_category (id, name) VALUES (13, '수험서/자격증');
INSERT INTO books_category (id, name) VALUES (14, '어린이');
INSERT INTO books_category (id, name) VALUES (15, '에세이');
INSERT INTO books_category (id, name) VALUES (16, '여행');
INSERT INTO books_category (id, name) VALUES (17, '역사');
INSERT INTO books_category (id, name) VALUES (18, '예술/대중문화');
INSERT INTO books_category (id, name) VALUES (19, '외국어');
INSERT INTO books_category (id, name) VALUES (20, '유아');
INSERT INTO books_category (id, name) VALUES (21, '인문학');
INSERT INTO books_category (id, name) VALUES (22, '일본 도서');
INSERT INTO books_category (id, name) VALUES (23, '자기계발');
INSERT INTO books_category (id, name) VALUES (24, '잡지');
INSERT INTO books_category (id, name) VALUES (25, '장르소설');
INSERT INTO books_category (id, name) VALUES (26, '전집/중고전집');
INSERT INTO books_category (id, name) VALUES (27, '종교/역학');
INSERT INTO books_category (id, name) VALUES (28, '좋은부모');
INSERT INTO books_category (id, name) VALUES (29, '중학교참고서');
INSERT INTO books_category (id, name) VALUES (30, '청소년');
INSERT INTO books_category (id, name) VALUES (31, '청소년_추천도서');
INSERT INTO books_category (id, name) VALUES (32, '초등학교참고서');
INSERT INTO books_category (id, name) VALUES (33, '컴퓨터/모바일');
INSERT INTO books_category (id, name) VALUES (34, 'Gift');
INSERT INTO books_category (id, name) VALUES (35, '가요');
INSERT INTO books_category (id, name) VALUES (36, '국악');
INSERT INTO books_category (id, name) VALUES (37, '상품권');
INSERT INTO books_category (id, name) VALUES (38, '오디오파일');
INSERT INTO books_category (id, name) VALUES (39, '월드뮤직');
INSERT INTO books_category (id, name) VALUES (40, '재즈');
INSERT INTO books_category (id, name) VALUES (41, '종교/명상/기타');
INSERT INTO books_category (id, name) VALUES (42, '증정용 음악상품권');
INSERT INTO books_category (id, name) VALUES (43, '클래식');
INSERT INTO books_category (id, name) VALUES (44, '팝');
INSERT INTO books_category (id, name) VALUES (45, '해외구매');
INSERT INTO books_category (id, name) VALUES (46, 'J-Pop');
INSERT INTO books_category (id, name) VALUES (47, 'LP');
INSERT INTO books_category (id, name) VALUES (48, 'O.S.T.');
INSERT INTO books_category (id, name) VALUES (49, '고전/명작');
INSERT INTO books_category (id, name) VALUES (50, '공포/스릴러');
INSERT INTO books_category (id, name) VALUES (51, '교양/다큐멘터리');
INSERT INTO books_category (id, name) VALUES (52, '교육용 S/W');
INSERT INTO books_category (id, name) VALUES (53, '드라마/코미디');
INSERT INTO books_category (id, name) VALUES (54, '박스세트');
INSERT INTO books_category (id, name) VALUES (55, '블루레이');
INSERT INTO books_category (id, name) VALUES (56, '성인');
INSERT INTO books_category (id, name) VALUES (57, '애니메이션');
INSERT INTO books_category (id, name) VALUES (58, '액션/어드벤처');
INSERT INTO books_category (id, name) VALUES (59, '유아/아동');
INSERT INTO books_category (id, name) VALUES (60, '음악DVD');
INSERT INTO books_category (id, name) VALUES (61, '제작국가별');
INSERT INTO books_category (id, name) VALUES (62, '취미/스포츠');
INSERT INTO books_category (id, name) VALUES (63, 'S.F/판타지');
INSERT INTO books_category (id, name) VALUES (64, 'TV 시리즈');
INSERT INTO books_category (id, name) VALUES (65, 'VCD');
INSERT INTO books_category (id, name) VALUES (66, 'VHS (비디오테이프)');
INSERT INTO books_category (id, name) VALUES (67, '가정/원예/인테리어');
INSERT INTO books_category (id, name) VALUES (68, '가족/관계');
INSERT INTO books_category (id, name) VALUES (69, '건강/스포츠');
INSERT INTO books_category (id, name) VALUES (70, '건축/디자인');
INSERT INTO books_category (id, name) VALUES (71, '게임/토이');
INSERT INTO books_category (id, name) VALUES (72, '공예/취미/수집');
INSERT INTO books_category (id, name) VALUES (73, '교육/자료');
INSERT INTO books_category (id, name) VALUES (74, '기술공학');
INSERT INTO books_category (id, name) VALUES (75, '기타');
INSERT INTO books_category (id, name) VALUES (76, '기타 언어권 도서');
INSERT INTO books_category (id, name) VALUES (77, '달력/다이어리/연감');
INSERT INTO books_category (id, name) VALUES (78, '대만도서');
INSERT INTO books_category (id, name) VALUES (79, '대학교재');
INSERT INTO books_category (id, name) VALUES (80, '독일 도서');
INSERT INTO books_category (id, name) VALUES (81, '문구/비도서');
INSERT INTO books_category (id, name) VALUES (82, '법률');
INSERT INTO books_category (id, name) VALUES (83, '수험서');
INSERT INTO books_category (id, name) VALUES (84, '스페인 도서');
INSERT INTO books_category (id, name) VALUES (85, '언어학');
INSERT INTO books_category (id, name) VALUES (86, '오디오북');
INSERT INTO books_category (id, name) VALUES (87, '요리');
INSERT INTO books_category (id, name) VALUES (88, '유머');
INSERT INTO books_category (id, name) VALUES (89, '의학');
INSERT INTO books_category (id, name) VALUES (90, '인문/사회');
INSERT INTO books_category (id, name) VALUES (91, '자연과학');
INSERT INTO books_category (id, name) VALUES (92, '전기/자서전');
INSERT INTO books_category (id, name) VALUES (93, '종교/명상/점술');
INSERT INTO books_category (id, name) VALUES (94, '중국 도서');
INSERT INTO books_category (id, name) VALUES (95, '컴퓨터');
INSERT INTO books_category (id, name) VALUES (96, '한국관련도서');
INSERT INTO books_category (id, name) VALUES (97, '해외잡지');
INSERT INTO books_category (id, name) VALUES (98, 'ELT/어학/사전');
INSERT INTO books_category (id, name) VALUES (99, '19+');
INSERT INTO books_category (id, name) VALUES (100, 'BL');
INSERT INTO books_category (id, name) VALUES (101, '구텐베르크 원서');
INSERT INTO books_category (id, name) VALUES (102, '라이트 노벨');
INSERT INTO books_category (id, name) VALUES (103, '로맨스');
INSERT INTO books_category (id, name) VALUES (104, '사전/기타');
INSERT INTO books_category (id, name) VALUES (105, '알라딘오디오북');
INSERT INTO books_category (id, name) VALUES (106, '인물/평전');
INSERT INTO books_category (id, name) VALUES (107, '중고등참고서');
INSERT INTO books_category (id, name) VALUES (108, '초등참고서');
INSERT INTO books_category (id, name) VALUES (109, '판타지/무협');
INSERT INTO books_category (id, name) VALUES (110, '해외도서');