# Generated by Django 5.2.9 on 2025-12-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_library_unique_user_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='current_page',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
