# Generated by Django 5.2.9 on 2025-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_library_current_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[('want', '읽고 싶은 책'), ('reading', '읽고 있는 책'), ('finished', '다 읽은 책')], max_length=20),
        ),
    ]
