# Generated by Django 5.2.9 on 2025-12-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author_alter_book_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('external_cid', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_mappings', to='books.category')),
            ],
        ),
    ]
