# Generated by Django 5.2.9 on 2025-12-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_externalcategorymapping'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='externalcategorymapping',
            table='external_category_mapping',
        ),
    ]
