# Generated by Django 5.2.9 on 2025-12-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_externalcategorymapping_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='externalcategorymapping',
            table='books_external_category_mapping',
        ),
    ]
