# Generated by Django 5.2.9 on 2025-12-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_externalcategorymapping_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcategorymapping',
            name='external_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='externalcategorymapping',
            unique_together={('provider', 'external_cid')},
        ),
    ]
