# Generated by Django 5.2.9 on 2025-12-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_externalcategorymapping_external_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalcategorymapping',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='externalcategorymapping',
            name='external_cid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='externalcategorymapping',
            name='external_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
