# Generated by Django 5.2.9 on 2025-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_externalcategorymapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcategorymapping',
            name='provider',
            field=models.CharField(max_length=30),
        ),
    ]
