# Generated by Django 5.2.9 on 2025-12-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_externalcategorymapping_provider'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='externalcategorymapping',
            constraint=models.UniqueConstraint(fields=('provider', 'external_cid'), name='uq_ext_category_map_provider_cid'),
        ),
    ]
