# Generated by Django 5.2.9 on 2025-12-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_externalcategorymapping_uq_ext_category_map_provider_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(null=True),
        ),
    ]
