# Generated by Django 5.2.9 on 2025-12-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcategorymapping',
            name='external_cid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='externalcategorymapping',
            name='external_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
