# Generated by Django 5.2.9 on 2025-12-21 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_content'),
        ('galfies', '0002_alter_galfy_book_alter_galfy_page_number_and_more'),
        ('reviews', '0002_alter_review_book_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='galfy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='galfies.galfy'),
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review'),
        ),
    ]
