# Generated by Django 5.2.9 on 2025-12-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_galfy_comment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='target_id',
        ),
    ]
