# Generated by Django 5.2.9 on 2025-12-19 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_externalcategorymapping_uq_ext_category_map_provider_cid'),
        ('galfies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='galfy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galfies', to='books.book'),
        ),
        migrations.AlterField(
            model_name='galfy',
            name='page_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='galfy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galfies', to=settings.AUTH_USER_MODEL),
        ),
    ]
